import { Database } from "lucide-react";

interface SourcesFooterProps {
  sources: string[];
}

function renderSource(source: string) {
  const parts = source.split(': ');
  if (parts.length < 2) {
    return <span>{source}</span>;
  }

  const category = parts[0];
  const name = parts[1];

  let url = '';
  if (name.includes('Financial Modeling Prep')) {
    url = 'https://site.financialmodelingprep.com/';
  } else if (name.includes('Finnhub')) {
    url = 'https://finnhub.io/';
  } else if (name.includes('OpenRouter')) {
    url = 'https://openrouter.ai/';
  }

  return (
    <span className="inline-flex items-center gap-1">
      <span className="text-text-muted font-normal">{category}: </span>
      {url ? (
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          className="text-accent hover:underline font-semibold"
        >
          {name}
        </a>
      ) : (
        <span className="font-semibold text-text-primary">{name}</span>
      )}
    </span>
  );
}

export default function SourcesFooter({ sources }: SourcesFooterProps) {
  if (!sources || sources.length === 0) return null;

  return (
    <div className="bg-bg-card border border-border rounded-2xl p-6 space-y-4">
      {/* Header */}
      <div className="flex items-center gap-2">
        <Database className="w-5 h-5 text-accent" />
        <h3 className="text-text-primary font-semibold text-lg">
          Data Sources &amp; Attributions
        </h3>
      </div>

      {/* Source pills */}
      <div className="flex flex-wrap gap-2">
        {sources.map((source) => (
          <span
            key={source}
            className="inline-flex items-center px-3.5 py-2 rounded-full text-xs bg-bg-input border border-border text-text-secondary"
          >
            {renderSource(source)}
          </span>
        ))}
      </div>

      {/* Disclaimer */}
      <p className="text-text-muted text-xs leading-relaxed">
        All financial metrics, descriptions, and news headlines are fetched in real-time from verified endpoints. Quantitative scores are computed deterministically. Moat analysis, risk profiles, and recommendation explanations are generated by OpenRouter.
      </p>
    </div>
  );
}
